version: '3.4'

services:
  swb:
    image: swb:latest
    restart: always
    depends_on:
      bot_db:
        condition: service_healthy
    env_file: .env
    networks:
      - backend
  bot_db:
    image: postgres:15.4
    restart: always
    ports:
      - '5432:5432'
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    env_file: .env

networks:
  backend:
